### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by chardetm** [AaronO/kpop#1]
Hi AaronO, I would like to use your kpop library in my Korean numbers learning tool. My tool is non-commercial so I guess it is fine, but just to clarify things would you consider choosing a license for your library?

**Comment by AaronO** [comment]
@chardetm There's no `LICENSE` file in the repo, but there's a license field in the `package.json`.

It's under `ISC` (https://github.com/AaronO/kpop/blob/master/package.json#L230), which a very liberal BSD-like license.

I built `kpop` because I needed it for a mobile app I was building.

You're more than welcome to use it.

**Comment by chardetm** [comment]
Sorry I didn't see that, thanks for your reply!
